apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.database.name }}
    namespace: {{ .Values.global.namespace }}-{{ .Values.global.env }}
    labels:
        name: {{ .Values.database.service.labels.name }}
spec:
    type: ClusterIP
    selector:
        name: {{ .Values.database.name }}-pod
        type: postgres-db
    ports:
        - port: {{ .Values.database.service.ports.port }}
          targetPort: {{ .Values.database.service.ports.targetPort }}